build: patch around qt duplicate symbol issue
This is currently causing the same failure in two different cases:

   ```bash
    duplicate symbol 'lcQpaFonts()' in:
        /tmp/build/depends/x86_64-apple-darwin/lib/libQt5ThemeSupport.a(qgenericunixthemes.o)
        /tmp/build/depends/x86_64-apple-darwin/lib/libQt5FontDatabaseSupport.a(qfontengine_coretext.o)
    ld: 1 duplicate symbol for architecture x86_64
    ```

    ```bash
    x86_64-apple-darwin-ld: error: duplicate symbol: __Z10lcQpaFontsv
    >>> defined in /tmp/build/depends/x86_64-apple-darwin/lib/libQt5ThemeSupport.a(qgenericunixthemes.o)
    >>> defined in /tmp/build/depends/x86_64-apple-darwin/lib/libQt5FontDatabaseSupport.a(qfontengine_coretext.o)
    ```

    Co-authored-by: Hennadii Stepanov <32963518+hebasto@users.noreply.github.com>