Make rpc-tests properly execute electrum tests when explicitly list at command line
WhenElectrumFound() add a "--electrum.exec=" argument to electrum tests even if we did not pass it
at the command line, so we need to special-case electrum tests while checking for cmd line arguments
otherwise they won't be run cause no electrum.exec has been added to "passOn" array

Without this MR the following cmd:

qa/pull-tester/rpc_tests.py electrum_token_genesis_info

will fail with this error message:

Error: electrum_token_genesis_info is not a known test.